print('======Desafio 04======')
t = input('Escreva seu texto')
print()
print('O tipo primitivo é: ', type(t))
print('Só tem espaços? ', t.isspace())
print('É alfabetico ? ',t.isalpha())
print('É alfanumerico? ', t.isalnum())
print('É um número? ',t.isnumeric())
print('É minúscula? ',t.islower())
print('É maiúscula? ',t.isupper())
